#!/bin/bash

#SBATCH --job-name=GMAP_augustus_coding_sequence
#SBATCH --mail-user=athimed.eltaher@unibas.ch
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,ARRAY_TASKS
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=50G
#SBATCH --qos=6hours
#SBATCH --time=6:00:00
#SBATCH --array=7-7
#SBATCH --output=/scicore/home/salzburg/eltaher/astrid_data/scicore_report/GMAP_augustus_coding_sequence_out.o
#SBATCH --error=/scicore/home/salzburg/eltaher/astrid_data/scicore_report/GMAP_augustus_coding_sequence_err.o
#SBATCH --workdir=/scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence

module load GMAP-GSNAP/2017-08-15-goolf-1.7.20
module load SAMtools/1.3.1-goolf-1.7.20


export SPECIES=`cat /scicore/home/salzburg/eltaher/cichlidX/data/dNdS_genomes/speciesList.txt | head -n $SLURM_ARRAY_TASK_ID | tail -n 1`

mkdir /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}

##
/scicore/soft/apps/GMAP-GSNAP/2017-08-15-goolf-1.7.20/bin/gmap -D /scicore/home/salzburg/GROUP/RNA_seq/FASTA_GTF_GFF -d otilapia -f gff3_gene -n 1 -t 4 --min-trimmed-coverage 0.5 --min-identity 0.8 /scicore/home/salzburg/eltaher/cichlidX/result/Augustus/${SPECIES}/GenePrediction_Augustus_${SPECIES}3.codingseq > /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80.gff3
/scicore/soft/apps/GMAP-GSNAP/2017-08-15-goolf-1.7.20/bin/gmap -D /scicore/home/salzburg/GROUP/RNA_seq/FASTA_GTF_GFF -d otilapia -f samse -n 1 -t 4 --min-trimmed-coverage 0.5 --min-identity 0.8 /scicore/home/salzburg/eltaher/cichlidX/result/Augustus/${SPECIES}/GenePrediction_Augustus_${SPECIES}3.codingseq > /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80.sam


##
samtools view -b -h -F 4 /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80.sam > /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80_mapped.bam
samtools sort /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80_mapped.bam -o /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80_mapped.sortedByCoord.out.bam
samtools fasta /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80_mapped.sortedByCoord.out.bam > /scicore/home/salzburg/eltaher/cichlidX/result/GMAP/augustus_coding_sequence/${SPECIES}/GMAP_GenePrediction_Augustus_${SPECIES}_codingseq_qcov50_iden80_mapped.sortedByCoord.out.fasta

