#!/bin/bash

#SBATCH --job-name=GenePrediction_Augustus_DNAssembly
#SBATCH --mail-user=athimed.eltaher@unibas.ch
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,ARRAY_TASKS
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=10G
#SBATCH --qos=1week
#SBATCH --time=7-0:00:00
#SBATCH --array=9,17,28,128,152,252,407
#SBATCH --output=/scicore/home/salzburg/eltaher/cichlidX/scicore_report/GenePrediction_Augustus_DNAssembly_out.o
#SBATCH --error=/scicore/home/salzburg/eltaher/cichlidX/scicore_report/GenePrediction_Augustus_DNAssembly_err.o
#SBATCH --workdir=/scicore/home/salzburg/eltaher/cichlidX/result/Augustus

module load Augustus/3.2.3-goolf-1.7.20
module load SAMtools/1.3.1-goolf-1.7.20

export SPECIES=`cat /scicore/home/salzburg/eltaher/cichlidX/data/dNdS_genomes/speciesList.txt | head -n $SLURM_ARRAY_TASK_ID | tail -n 1`

mkdir /scicore/home/salzburg/eltaher/cichlidX/result/Augustus/${SPECIES}

AUGUSTUS_CONFIG_PATH="/scicore/soft/apps/Augustus/3.2.3-goolf-1.7.20/config"
export $AUGUSTUS_CONFIG_PATH

/scicore/soft/apps/Augustus/3.2.3-goolf-1.7.20/bin/augustus --species=zebrafish --strand=both --genemodel=partial --gff3=on --protein=on --codingseq=on --outfile=/scicore/home/salzburg/eltaher/cichlidX/result/Augustus/${SPECIES}/GenePrediction_Augustus_${SPECIES}.gff3 /scicore/home/boehne/GROUP/GenomeAssemblyCichlidX/ready_assemblies/${SPECIES}/${SPECIES}.scf.fasta
